eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: serviceProvideDemo
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
test_words: 'i love you,baby!!!!'
words: 'hello world!!!!'
